### ISSUE TITLE
Fix asm for LTO on ARM

### ISSUE THREAD

**Issue by arter97** [andikleen/linux-misc#11]
So, I've managed to merge LTO changes from this github repository to a ARM Linux 3.4 kernel.

With plugin enabled gcc-ar, I've managed to get almost every errors passed until this happened;

  LDFINAL  .tmp_vmlinux1
/tmp/ccxBqOkb.ltrans31.ltrans.o: In function `kernel_thread':
ccxBqOkb.ltrans31.o:(.text+0x6a74): undefined reference to `kernel_thread_exit'
ccxBqOkb.ltrans31.o:(.text+0x6a78): undefined reference to `kernel_thread_helper'
ccxBqOkb.ltrans31.o:(.text+0x6a8c): undefined reference to `kernel_thread_exit'
ccxBqOkb.ltrans31.o:(.text+0x6a90): undefined reference to `kernel_thread_helper'
`kprobe_handler' referenced in section `.kprobes.text' of /tmp/ccxBqOkb.ltrans31.ltrans.o: defined in discarded section `.text' of arch/arm/kernel/built-in.o (symbol from plugin)
collect2: error: ld returned 1 exit status
make: *** [.tmp_vmlinux1] Error 1

The 'kernel_thread', 'kernel_thread_exit', 'kernel_thread_helper' is declared in arch/arm/kernel/process.c, but it's "asm" function seems to be not working with LTO.

How can I fix those errors??

Thanks!

PS1. My kernel has CONFIG_ARM_UNWIND enabled;
PS2. The latest Linux kernels apparently doesn't have those kernel_thread functions on arch/arm/kernel/process.c.

**Comment by rmbq** [comment]
Fixed with this commit: https://github.com/rmbq/android_kernel_lge_hammerhead/commit/b174c8a001da10283c792414a51e5114627a4495

patch:
From b174c8a001da10283c792414a51e5114627a4495 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Davide=20Rombol=C3=A0?= <davide.rombola@gmail.com>
Date: Wed, 23 Dec 2015 08:03:03 +0100
Subject: [PATCH] arm: kernel: mark kernel_thread_helper and kernel_thread_exit
 functions as global

---
 arch/arm/kernel/process.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/arch/arm/kernel/process.c b/arch/arm/kernel/process.c
index 4d24305..2160c96 100644
--- a/arch/arm/kernel/process.c
+++ b/arch/arm/kernel/process.c
@@ -582,6 +582,7 @@ extern void kernel_thread_helper(void);
 asm(	".pushsection .text\n"
 "	.align\n"
 "	.type	kernel_thread_helper, #function\n"
+"	.global kernel_thread_helper\n"
 "kernel_thread_helper:\n"
 #ifdef CONFIG_TRACE_IRQFLAGS
 "	bl	trace_hardirqs_on\n"
@@ -598,6 +599,7 @@ extern void kernel_thread_exit(long code);
 asm(	".pushsection .text\n"
 "	.align\n"
 "	.type	kernel_thread_exit, #function\n"
+"	.global kernel_thread_exit\n"
 "kernel_thread_exit:\n"
 "	.fnstart\n"
 "	.cantunwind\n"

**Comment by andikleen** [comment]
Thanks.

I checked upstream and it looks like the function has been removed completely there. So I assume it's resolved in the latest trees.
